# [Array Mathematics](https://www.hackerrank.com/challenges/np-array-mathematics/problem?h_r=next-challenge&h_v=zen)
<pre>
Basic mathematical functions operate element-wise on arrays. They are available both as operator overloads and as functions in the NumPy module.

import numpy

a = numpy.array([1,2,3,4], float)
b = numpy.array([5,6,7,8], float)

print a + b                     #[  6.   8.  10.  12.]
print numpy.add(a, b)           #[  6.   8.  10.  12.]

print a - b                     #[-4. -4. -4. -4.]
print numpy.subtract(a, b)      #[-4. -4. -4. -4.]

print a * b                     #[  5.  12.  21.  32.]
print numpy.multiply(a, b)      #[  5.  12.  21.  32.]

print a / b                     #[ 0.2         0.33333333  0.42857143  0.5       ]
print numpy.divide(a, b)        #[ 0.2         0.33333333  0.42857143  0.5       ]

print a % b                     #[ 1.  2.  3.  4.]
print numpy.mod(a, b)           #[ 1.  2.  3.  4.]

print a**b                      #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]
print numpy.power(a, b)         #[  1.00000000e+00   6.40000000e+01   2.18700000e+03   6.55360000e+04]</pre>

In [23]:
import numpy as np
n1,n2=map(int,input().split())
a1=np.zeros((n1,n2),int)
a2=np.zeros((n1,n2),int)

for i in range(n1):
    a1[i]=np.array(input().split(),int)

for i in range(n1):
    a2[i]=np.array(input().split(),int)


np.set_printoptions(legacy='1.13')
    
print(f'{(a1+a2).astype(int)}\n{(a1-a2).astype(int)}\n{(a1*a2).astype(int)}\n{(a1//a2).astype(int)}\n{(a1%a2).astype(int)}\n{(a1**a2).astype(int)}\n')

 1 4
 1 2 3 4
 5 6 7 8


[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]



In [31]:
a1=np.zeros((n1,n2),int)
# a1[0]=np.array(input().split(),int)
a1[0]

array([0, 0, 0, 0])

In [15]:
np.zeros((2,2),int)

array([[0, 0],
       [0, 0]])

# [Floor, Ceil and Rint](https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?h_r=next-challenge&h_v=zen)

<pre>
<b>floor</b>
The tool floor returns the floor of the input element-wise.
The floor of  is the largest integer  where .

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.floor(my_array)         #[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]

<b>ceil</b>
The tool ceil returns the ceiling of the input element-wise.
The ceiling of  is the smallest integer  where .

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.ceil(my_array)          #[  2.   3.   4.   5.   6.   7.   8.   9.  10.]

<b>rint</b>
The rint tool rounds to the nearest integer of input element-wise.

import numpy

my_array = numpy.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9])
print numpy.rint(my_array)          #[  1.   2.   3.   4.   6.   7.   8.   9.  10.]
</pre>

In [1]:
import numpy as np
a=np.array(input().split(),float)
np.set_printoptions(legacy='1.13')
print(np.floor(a))
print(np.ceil(a))
print(np.rint(a))

 1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9


[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# [Sum and Prod](https://www.hackerrank.com/challenges/np-sum-and-prod/problem)
**1. sum**

The sum tool returns the sum of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.sum(my_array, axis = 0)         #Output : [4 6]\
print numpy.sum(my_array, axis = 1)         #Output : [3 7]\
print numpy.sum(my_array, axis = None)      #Output : 10\
print numpy.sum(my_array)                   #Output : 10\
By default, the axis value is ***None***. Therefore, it performs a sum over all the dimensions of the input array


**2. prod**

The prod tool returns the product of array elements over a given axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.prod(my_array, axis = 0)            #Output : [3 8]\
print numpy.prod(my_array, axis = 1)            #Output : [ 2 12]\
print numpy.prod(my_array, axis = None)         #Output : 24\
print numpy.prod(my_array)                      #Output : 24\
By default, the axis value is ***None***. Therefore, it performs the product over all the dimensions of the input array.

In [ ]:
n=

In [1]:
import numpy as np

#### SUM

In [3]:
a1=np.array([[1,2],[3,4]])
a1

array([[1, 2],
       [3, 4]])

In [5]:
np.sum(a1,axis=0)#column wise addition

array([4, 6])

In [6]:
np.sum(a1,axis=1)#row wise sum

array([3, 7])

In [7]:
np.sum(a1)#all elemnts sum by default

10

#### PROD(MUL)

In [8]:
np.prod(a1,axis=0)#column wise addition

array([3, 8])

In [9]:
np.prod(a1,axis=1)#row wise sum

array([ 2, 12])

In [10]:
np.prod(a1)#all elemnts sum by default

24

In [11]:
import numpy as np

n1,n2=input().split(' ')
a=[]
for _ in range(int(n1)):
    a.append(list(map(int,input().split())))
ar=np.array(a)
print(np.prod(np.sum(ar,axis=0)))

 2 2
 1 2
 3 4


24


# [Min and Max](https://www.hackerrank.com/challenges/np-min-and-max/problem)


**min**

The tool min returns the minimum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], \
                        [3, 7],\
                        [1, 3],\
                        [4, 0]])

print numpy.min(my_array, axis = 0)         #Output : [1 0]\
print numpy.min(my_array, axis = 1)         #Output : [2 3 1 0]\
print numpy.min(my_array, axis = None)      #Output : 0\
print numpy.min(my_array)                   #Output : 0\
By default, the axis value is ***None***. Therefore, it finds the minimum over all the dimensions of the input array.

**max**

The tool max returns the maximum value along a given axis.

import numpy

my_array = numpy.array([[2, 5], \
                        [3, 7],\
                        [1, 3],\
                        [4, 0]])

print numpy.max(my_array, axis = 0)         #Output : [4 7]\
print numpy.max(my_array, axis = 1)         #Output : [5 7 3 4]\
print numpy.max(my_array, axis = None)      #Output : 7\
print numpy.max(my_array)                   #Output : 7\
By default, the axis value is ***None***. Therefore, it finds the maximum over all the dimensions of the input array.

In [12]:
import numpy as np
n1,n2=map(int,input().split())
a=[]
for _ in range(int(n1)):
    a.append(list(map(int,input().split())))
ar=np.array(a)
print(np.max(np.min(ar,axis=1)))

 4 2
 2 5
 3 7
 1 3
 4 0


3


# [Mean, Var, and Std](https://www.hackerrank.com/challenges/np-mean-var-and-std/problem)

**mean**

The mean tool computes the arithmetic mean along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.mean(my_array, axis = 0)        #Output : [ 2.  3.]\
print numpy.mean(my_array, axis = 1)        #Output : [ 1.5  3.5]\
print numpy.mean(my_array, axis = None)     #Output : 2.5\
print numpy.mean(my_array)                  #Output : 2.5\
By default, the axis is ***None***. Therefore, it computes the mean of the flattened array.

**var**

The var tool computes the arithmetic variance along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.var(my_array, axis = 0)         #Output : [ 1.  1.]\
print numpy.var(my_array, axis = 1)         #Output : [ 0.25  0.25]\
print numpy.var(my_array, axis = None)      #Output : 1.25\
print numpy.var(my_array)                   #Output : 1.25\
By default, the axis is ***None***. Therefore, it computes the variance of the flattened array.

**std**

The std tool computes the arithmetic standard deviation along the specified axis.

import numpy

my_array = numpy.array([ [1, 2], [3, 4] ])

print numpy.std(my_array, axis = 0)         #Output : [ 1.  1.]\
print numpy.std(my_array, axis = 1)         #Output : [ 0.5  0.5]\
print numpy.std(my_array, axis = None)      #Output : 1.11803398875\
print numpy.std(my_array)                   #Output : 1.11803398875\
By default, the axis is ***None***. Therefore, it computes the standard deviation of the flattened array.

In [3]:
import numpy as np
n1,n2=map(int,input().split())
a=[]
for _ in range(int(n1)):
    a.append(list(map(int,input().split())))
ar=np.array(a)
np.set_printoptions(legacy='1.13')
print(np.mean(ar,axis=1))
print(np.var(ar,axis=0))
print(np.std(ar))

 2 2
 1 2
 3 4


[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# [Transpose and Flatten](https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem)
<pre>
<b>Transpose</b>

We can generate the transposition of an array using the tool numpy.transpose.
It will not affect the original array, but it will create a new array.

import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print numpy.transpose(my_array)

#Output
[[1 4]
 [2 5]
 [3 6]]

<b>Flatten</b>

The tool flatten creates a copy of the input array flattened to one dimension.

import numpy

my_array = numpy.array([[1,2,3],
                        [4,5,6]])
print my_array.flatten()

#Output
[1 2 3 4 5 6]</pre>

In [16]:
import numpy as np
n1,n2=map(int,input().split())
a=[]
for _ in range(int(n1)):
    a.append(list(map(int,input().split())))
ar=np.array(a)
np.set_printoptions(legacy='1.13')
print(np.transpose(ar))

 3 2
 1 2
 3 4
 5 6


[[1 3 5]
 [2 4 6]]


In [18]:
print(ar.flatten())

[1 2 3 4 5 6]


# [Eye and Identity](https://www.hackerrank.com/challenges/np-eye-and-identity/problem)

<pre>
<b>identity</b>

The identity tool returns an identity array. An identity array is a square matrix with all the main diagonal elements as  and the rest as . The default type of elements is float.

import numpy
print numpy.identity(3) #3 is for  dimension 3 X 3

#Output
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

<b>eye</b>

The eye tool returns a 2-D array with 's as the diagonal and 's elsewhere. The diagonal can be main, upper or lower depending on the optional parameter . A positive  is for the upper diagonal, a negative  is for the lower, and a   (default) is for the main diagonal.

import numpy
print numpy.eye(8, 7, k = 1)    # 8 X 7 Dimensional array with first upper diagonal 1.

#Output
[[ 0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.]]

print numpy.eye(8, 7, k = -2)   # 8 X 7 Dimensional array with second lower diagonal 1.

</pre>

In [1]:
import numpy as np
n1,n2=map(int,input().split())
np.set_printoptions(legacy='1.13')
print(np.eye(n1,n2))

 3 3


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# [Dot and Cross](https://www.hackerrank.com/challenges/np-dot-and-cross/problem)


**dot**

The dot tool returns the dot product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])\
B = numpy.array([ 3, 4 ])

print numpy.dot(A, B)       #Output : 11

**cross**

The cross tool returns the cross product of two arrays.

import numpy

A = numpy.array([ 1, 2 ])\
B = numpy.array([ 3, 4 ])

print numpy.cross(A, B)     #Output : -2

In [5]:
import numpy as np
n=int(input())
a1=[]
a2=[]

for _ in range(int(n)):
    a1.append(list(map(int,input().split())))
for _ in range(int(n)):
    a2.append(list(map(int,input().split())))
ar_a1=np.array(a1)
ar_a2=np.array(a2)

np.set_printoptions(legacy='1.13')
print(np.dot(ar_a1,ar_a2))
print(np.cross(ar_a1,ar_a2))

 2
 1 2
 3 4
 1 2
 3 4


[[ 7 10]
 [15 22]]
[0 0]


![Cross](cross.png)

# [Inner and Outer](https://www.hackerrank.com/challenges/np-inner-and-outer/problem)

**inner**

The inner tool returns the inner product of two arrays.

import numpy

A = numpy.array([0, 1])\
B = numpy.array([3, 4])

print numpy.inner(A, B)     #Output : 4

**outer**

The outer tool returns the outer product of two arrays.

import numpy

A = numpy.array([0, 1])
B = numpy.array([3, 4])

print numpy.outer(A, B)     #Output : [[0 0]
                            #          [3 4]]

In [ ]:
import numpy as np
a1=list(map(int,input().split()))
a2=list(map(int,input().split()))

ar_a1=np.array(a1)
ar_a2=np.array(a2)

print(np.inner(ar_a1,ar_a2))
print(np.outer(ar_a1,ar_a2))

In [2]:
import numpy as np
n=int(input())
a1=[]
a2=[]

for _ in range(int(n)):
    a1.append(list(map(int,input().split())))
for _ in range(int(n)):
    a2.append(list(map(int,input().split())))
ar_a1=np.array(a1)
ar_a2=np.array(a2)

print(np.inner(ar_a1,ar_a2))
print(np.outer(ar_a1,ar_a2))

 2
 1 2
 3 4
 11 12
 13 14


[[35 41]
 [81 95]]
[[11 12 13 14]
 [22 24 26 28]
 [33 36 39 42]
 [44 48 52 56]]


In [3]:
'''

np.inner:
1*11+2*12, 1*13+2*14 
3*11+4*12, 3*13+4*14

'''

'\n1*11+2*12, 1*13+2*14 \n3*11+4*12, 3*13+4*14 \n'

# [Polynomials](https://www.hackerrank.com/challenges/np-polynomials/problem)

**poly**

The poly tool returns the coefficients of a polynomial with the given sequence of roots.

print numpy.poly([-1, 1, 1, 10])        #Output : [  1 -11   9  11 -10]

**roots**

The roots tool returns the roots of a polynomial with the given coefficients.

print numpy.roots([1, 0, -1])           #Output : [-1.  1.]

**polyint**

The polyint tool returns an antiderivative (indefinite integral) of a polynomial.

print numpy.polyint([1, 1, 1])          #Output : [ 0.33333333  0.5         1.          0.        ]

**polyder**

The polyder tool returns the derivative of the specified order of a polynomial.

print numpy.polyder([1, 1, 1, 1])       #Output : [3 2 1]

**polyval**

The polyval tool evaluates the polynomial at specific value.

print numpy.polyval([1, -2, 0, 2], 4)   #Output : 34

**polyfit**

The polyfit tool fits a polynomial of a specified order to a set of data using a least-squares approach.

print numpy.polyfit([0,1,-1, 2, -2], [0,1,1, 4, 4], 2)\
#Output :[  1.00000000e+00   0.00000000e+00  -3.97205465e-16]

The functions polyadd, polysub, polymul, and polydiv also handle proper addition, subtraction, multiplication, and division of polynomial coefficients, respectively.

In [1]:
import numpy as np

In [16]:
np.poly((2,-2))#roots of equation is passed to form equation

array([ 1.,  0., -4.])

 the above code represents
 $x**2-4$

In [17]:
np.roots((1,0,-4))#equation is passed to find roots of equation

array([-2.,  2.])

In [18]:
np.polyint((1,0,-4))#indefinite integral of equation

array([ 0.33333333,  0.        , -4.        ,  0.        ])

 the above code represents
 $x**3/3-x*4+c$ here c is 0

In [2]:
np.polyder((1,0,-4))# derivative

array([2, 0])

 the above code represents
 $x*2$

In [8]:
#evaluates the polynomial at specific value
np.polyval((1,0,-4),3) #at x=3

5

In [13]:
import numpy as np
a=list(map(float,input().split()))
val=int(input())
print(np.polyval(a,val))

 1.1 2 3
 0


3.0


# [Linear Algebra](https://www.hackerrank.com/challenges/np-linear-algebra/problem)

<pre>The NumPy module also comes with a number of built-in routines for linear algebra calculations. These can be found in the sub-module linalg.

<b>linalg.det</b>

The linalg.det tool computes the determinant of an array.

print numpy.linalg.det([[1 , 2], [2, 1]])       #Output : -3.0

<b>linalg.eig</b>

The linalg.eig computes the eigenvalues and right eigenvectors of a square array.

vals, vecs = numpy.linalg.eig([[1 , 2], [2, 1]])
print vals                                      #Output : [ 3. -1.]
print vecs                                      #Output : [[ 0.70710678 -0.70710678]
                                                #          [ 0.70710678  0.70710678]]
<b>linalg.inv</b>

The linalg.inv tool computes the (multiplicative) inverse of a matrix.

print numpy.linalg.inv([[1 , 2], [2, 1]])       #Output : [[-0.33333333  0.66666667]
                                                #          [ 0.66666667 -0.33333333]]</pre>

In [15]:
import numpy as np
a=[]
for _ in range(int(input())):
    a.append(list(map(float,input().split())))
np.set_printoptions(legacy='1.13')
print(np.linalg.det(a))

 2
 1 2
 2 1


-3.0
