In [8]:
import cv2
img=cv2.imread('0.jpeg')
# initilization of window
cv2.namedWindow('IMAGE',0)

cv2.imshow('IMAGE',img)
cv2.imwrite('output.jpeg',img)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
#access and understand pixel data
import cv2
import numpy as np
img=cv2.imread('0.jpeg')

print(img)
print(type(img))
print(len(img))
print(len(img[0]))
print(len(img[0][0]))
print(img.shape)
print(img.dtype)
print(img[:,:,0])      #red channel
print(img[10][15])


[[[ 24 146 162]
  [ 21 146 166]
  [ 16 147 174]
  ...
  [  7 146 172]
  [ 16 149 169]
  [ 23 155 172]]

 [[ 24 151 166]
  [ 22 151 170]
  [ 15 151 177]
  ...
  [  7 151 176]
  [ 13 152 171]
  [ 17 156 172]]

 [[ 22 159 175]
  [ 19 158 177]
  [ 14 157 184]
  ...
  [ 13 165 189]
  [ 14 164 181]
  [ 17 166 180]]

 ...

 [[  6 176 194]
  [  2 174 192]
  [  8 179 201]
  ...
  [  1 186 196]
  [  0 183 188]
  [  0 175 178]]

 [[  0 167 185]
  [  0 167 185]
  [  0 168 191]
  ...
  [  0 177 188]
  [  0 180 188]
  [  0 180 186]]

 [[  0 162 180]
  [  0 163 181]
  [  0 161 184]
  ...
  [  0 168 182]
  [  0 173 183]
  [  0 181 189]]]
<class 'numpy.ndarray'>
920
752
3
(920, 752, 3)
uint8
[[24 21 16 ...  7 16 23]
 [24 22 15 ...  7 13 17]
 [22 19 14 ... 13 14 17]
 ...
 [ 6  2  8 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]
[ 86 162 214]


In [15]:
# Data types and structures
import numpy as np
import cv2

black=np.zeros([150,150,1],'uint8')
cv2.imshow('black',black)
print(black[0,0,:])

ones=np.ones([150,150,3],'uint8')
# ones*=(2**8-1)
cv2.imshow('ones',ones)
print(ones[0,0,:])

white=np.ones([150,150,3],'uint16')
white*=(2**16-1)
cv2.imshow('white',white)
print(white[0,0,:])

#
color=ones.copy()
color[:,:]=(255,0,0) #blue
cv2.imshow('blue',color)
print(color[0,0,:])

cv2.waitKey(0)
cv2.destroyAllWindows()

[0]
[1 1 1]
[65535 65535 65535]
[255   0   0]


In [17]:
# image types and color channels
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('image',img)
cv2.moveWindow('image',0,0)

print(img.shape)
width,height,channel=img.shape

cv2.waitKey(0)
cv2.destroyAllWindows()

(920, 752, 3)


In [7]:
# pixel manipulation and filtering
import cv2
img=cv2.imread('0.jpeg',1)

gray=cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
cv2.imshow('KESHAV',gray)

r=img[:,:,0]
g=img[:,:,1]
b=img[:,:,2]

rgba=cv2.merge((r,g,b,g))
cv2.imshow('rgba',rgba)


cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# Gussian Blur,dilation and erosion
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('original',img)

# blur
blur=cv2.GaussianBlur(img,(5,55),0)
cv2.imshow('Gaussian Blur',blur)

kernel=np.ones((5,5),'uint8')
dilate=cv2.dilate(img,kernel,iterations=1)
erode=cv2.erode(img,kernel,iterations=1)

cv2.imshow('dilate',dilate)
cv2.imshow('erode',erode)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
# scale and rotate image
import numpy as np
import cv2
img=cv2.imread('0.jpeg',1)
cv2.imshow('original',img)

# scale
half=cv2.resize(img,(0,0),fx=0.5,fy=0.5,)
cv2.imshow('half',half)

stretch_=cv2.resize(img,(600,600),fx=0.5,fy=0.5)
cv2.imshow('stretch_',stretch_)

stretch_near_=cv2.resize(img,(600,600),fx=0.5,fy=0.5,interpolation = cv2.INTER_NEAREST)
cv2.imshow('stretch_near_',stretch_near_)

# rotate
M=cv2.getRotationMatrix2D((0,0),-30,1)
rotated=cv2.warpAffine(img,M,(img.shape[1],img.shape[0]))
cv2.imshow('rotated',rotated)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [6]:
# video inputs
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
while True:
    ret,frame=cap.read()
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [3]:
# create custom interface
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
# circle
color=(0,255,0)
point=(200,200)
radius=40
border_width=6

while True:
    ret,frame=cap.read()
    cv2.circle(frame,point,radius,color,border_width)
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [3]:
import numpy as np
import cv2
cap=cv2.VideoCapture(0)
# circle
color=(0,255,0)
point=(200,200)
radius=40
border_width=6
def click(event,x,y,flags,param):
    global point,pressed
    if event==cv2.EVENT_LBUTTONDOWN:
        print('Pressed: ',x,y)
        point=(x,y)
cv2.namedWindow('keshav')
cv2.setMouseCallback('keshav',click)
while True:
    ret,frame=cap.read()
    cv2.circle(frame,point,radius,color,border_width)
    cv2.imshow('keshav',frame)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

Pressed:  526 347
Pressed:  332 243


In [18]:
# Drawing App
import numpy as np
import cv2
# cap=cv2.VideoCapture(0)
keshav=np.ones([500,500,3],'uint8')*255
radius=3
color=(0,255,0)
pressed=False
def click(event,x,y,flags,param):
    global keshav,pressed
    if event==cv2.EVENT_LBUTTONDOWN:
        pressed=True
        cv2.circle(keshav,(x,y),radius,color,-1)
    elif event==cv2.EVENT_MOUSEMOVE and pressed==True:
        cv2.circle(keshav,(x,y),radius,color,-1)
    elif event==cv2.EVENT_LBUTTONUP:
        pressed=False
cv2.namedWindow('keshav')
cv2.setMouseCallback('keshav',click)

while True:
    cv2.imshow('keshav',keshav)
    if cv2.waitKey(1)&0xff==ord('q'):
        break
    elif cv2.waitKey(1)&0xff==ord('b'):
        color=(255,0,0)
    elif cv2.waitKey(1)&0xff==ord('g'):
        color=(0,255,0)
    elif cv2.waitKey(1)&0xff==ord('r'):
        color=(0,0,255)
cv2.destroyAllWindows()

In [12]:
# chapter 3
# segmentation
# simple threading
import numpy as np
import cv2
bw=cv2.imread('0.jpeg',0)
cv2.imshow('Original',bw)

'method1'
height,width=bw.shape[0:2]
binary=np.zeros([height,width,3],'uint8')
thresh=85
for row in range(0,height):
    for col in range(0,width):
        if bw[row][col]>thresh:
            binary[row][col]=255
cv2.imshow('binary',binary)

'method2'
ret,thresh=cv2.threshold(bw,thresh,255,cv2.THRESH_BINARY)
cv2.imshow('thresh',thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [9]:
# adaptive threading --->  https://www.geeksforgeeks.org/python-thresholding-techniques-using-opencv-set-2-adaptive-thresholding
import cv2
img=cv2.imread('sudoku.png',0)
cv2.imshow('Original',img)

# simaple threading ---> problem ---> uneven binding
ret,frame=cv2.threshold(img,85,255,cv2.THRESH_BINARY)
cv2.imshow('Binary',frame)

# adaptive threading ---> remove uneven binding
adap_thresh=cv2.adaptiveThreshold(img,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,115,1)
cv2.imshow('adaptive thresh',adap_thresh)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
# otsu threading ---> https://www.geeksforgeeks.org/python-thresholding-techniques-using-opencv-set-3-otsu-thresholding/
'We use the Traditional cv2.threshold function and use cv2.THRESH_OTSU as an extra flag.'
import cv2
img=cv2.imread('sudoku.png',0)
cv2.imshow('Original',img)

# simaple threading ---> problem ---> uneven binding
ret,frame=cv2.threshold(img,85,255,cv2.THRESH_BINARY)
cv2.imshow('Binary',frame)

# otsu
ret,frame=cv2.threshold(img,85,255,cv2.THRESH_BINARY+cv2.THRESH_OTSU)
cv2.imshow('Otsu',frame)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [12]:
# skin detection ---> 
import cv2
import numpy as np
img=cv2.imread('faces.jpeg',1)
hsv=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
cv2.imshow('HSV',hsv)

h=hsv[:,:,0]
s=hsv[:,:,1]
v=hsv[:,:,2]
hsv_split=np.concatenate((h,s,v),axis=1)
cv2.imshow('HSV_SPLIT',hsv_split)

# detect
ret,min_set=cv2.threshold(s,40,255,cv2.THRESH_BINARY)
ret,max_set=cv2.threshold(h,15,255,cv2.THRESH_BINARY)
final=cv2.bitwise_and(min_set,max_set)
cv2.imshow('Final',final)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
# object detection
import cv2
img=cv2.imread('detect_blob.png')
cv2.imshow('Original colored',img)
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
cv2.imshow('Original Gray',gray)


thresh=cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,115,1)
cv2.imshow('Thresh',thresh)

_,contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
img2=img.copy()
index=-1
thickness=5
color=(255,0,255)
cv2.drawContours(img2,contours,index,color,thickness)
cv2.imshow('Contours',img2)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [24]:
# Area, Perimeter, Center, Curvature
import numpy as np
import cv2

img=cv2.imread('detect_blob.png')
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
thresh=cv2.adaptiveThreshold(gray,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C,cv2.THRESH_BINARY,115,1)
_,contours,hierarchy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)

img2=img.copy()
color=(123,255,61)
index=-1
tk=2
frame=np.zeros([img.shape[0],img.shape[1],3],'uint8')
i=1
for c in contours:
    cv2.drawContours(frame,[c],index,color,tk)
    area=cv2.contourArea(c)
    arclength=cv2.arcLength(c,True)
    print('{} Area: {},  perimeter: {}'.format(i,area,arclength))
    i+=1
    m=cv2.moments(c)
    cx=int(m['m10']/m['m00'])
    cy=int(m['m01']/m['m00'])
    cv2.circle(frame,(cx,cy),1,(0,0,255),-1)
    cv2.imshow('Original',frame)
    
cv2.waitKey(0)
cv2.destroyAllWindows()

1 Area: 86.5,  perimeter: 45.55634891986847
2 Area: 959.5,  perimeter: 251.8406196832657
3 Area: 13091.5,  perimeter: 754.0416301488876
4 Area: 10069.5,  perimeter: 401.41421353816986
5 Area: 7780.0,  perimeter: 329.22034430503845
6 Area: 4160.0,  perimeter: 258.0
7 Area: 1672.0,  perimeter: 160.48528122901917
8 Area: 14515.0,  perimeter: 1225.768675327301
9 Area: 6569.0,  perimeter: 441.5979790687561
10 Area: 7701.0,  perimeter: 484.8284270763397
11 Area: 5581.0,  perimeter: 500.9604583978653
12 Area: 5019.0,  perimeter: 357.2792183160782
13 Area: 5019.0,  perimeter: 444.3675308227539
14 Area: 8826.0,  perimeter: 449.76449966430664
15 Area: 181.0,  perimeter: 54.62741661071777
16 Area: 551.5,  perimeter: 93.41421353816986
17 Area: 2708.5,  perimeter: 194.75230729579926
18 Area: 1644.5,  perimeter: 152.1248904466629
19 Area: 767.0,  perimeter: 105.74011433124542
20 Area: 3505.5,  perimeter: 251.0710676908493
21 Area: 8556.0,  perimeter: 345.70562493801117
22 Area: 8909.0,  perimeter: 3

In [46]:
# Canny edge detection
import cv2
import numpy

img=cv2.imread('tomatoes.jpg')
HSV=cv2.cvtColor(img,cv2.COLOR_BGR2HSV)
ret,thresh=cv2.threshold(HSV[:,:,0],25,255,cv2.THRESH_BINARY_INV)
cv2.imshow('thresh',thresh)

edges=cv2.Canny(img,100,70)
cv2.imshow('Edges',edges)

final=cv2.bitwise_or(thresh,edges)
cv2.imshow('Final',final)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [15]:
# CH-4 --> Face Detection
# Template Matching
import numpy as np
import cv2
template=cv2.imread('template.jpg')
frame=cv2.imread('players.jpg')
cv2.imshow('Template',template)
cv2.imshow('Frame',frame)

result=cv2.matchTemplate(frame,template,cv2.TM_CCOEFF_NORMED)
cv2.imshow('result1',result)
min_val,max_val,min_loc,max_loc=cv2.minMaxLoc(result)
cv2.circle(result,max_loc,15,255,-1)
cv2.imshow('result2',result)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [5]:
max_loc

(132, 243)

In [6]:
min_loc

(347, 191)

In [7]:
min_val

-0.43392035365104675

In [8]:
max_val

0.4392918348312378

In [31]:
# Face detection
import numpy as np
import cv2
img=cv2.imread('faces.jpeg')

rimg=cv2.resize(img,(img.shape[0]//3,img.shape[1]//5),interpolation=cv2.INTER_AREA)
gray=cv2.cvtColor(rimg,cv2.COLOR_BGR2GRAY)

path='haarcascade_frontalface_default.xml'

face_cascade=cv2.CascadeClassifier(path)
faces=face_cascade.detectMultiScale(gray,scaleFactor=1.25,minSize=(40,40))

for (x,y,w,h) in faces:
    cv2.rectangle(rimg,(x,y),(x+w,y+h),(0,255,0),1)
cv2.imshow('Img',rimg)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [42]:
# eye detection
import numpy as np
import cv2
img=cv2.imread('faces.jpeg')

rimg=cv2.resize(img,(img.shape[0]//3,img.shape[1]//5),interpolation=cv2.INTER_AREA)
gray=cv2.cvtColor(rimg,cv2.COLOR_BGR2GRAY)

path='haarcascade_eye.xml'

eye_cascade=cv2.CascadeClassifier(path)
eyes=eye_cascade.detectMultiScale(gray,scaleFactor=1.04,minNeighbors=20,minSize=(10,10))

for (x,y,w,h) in eyes:
    cx=(x+x+w)//2
    cy=(y+y+h)//2
    cv2.circle(rimg,(cx,cy),w//2,(255,0,0),2)
cv2.imshow('Img',rimg)

cv2.waitKey(0)
cv2.destroyAllWindows()